export default en = {
  welcome: "Hello",
  name: "Charlie",
  plName: "Enter your name",
  plEmail: "Enter your email",
  plPassword: "Enter your password",
  btnFortgotPass: "Forgot Password",
  btnLogin: "Login",
  btnRegister: "Register",
  tabFirst: "Home",
  tabSecond: "Network",
  tabThird: "Post",
  tabFourth: "Notification",
  tabFifth: "Chat",
};
